[domaincontrol.com] HTTPSConnectionPool(host='domaincontrol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc5eb07e350>: Failed to establish a new connection: [Errno 111] Connection refused'))
[fastly.net] HTTPSConnectionPool(host='www.fastly.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc5eb07dd10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[macromedia.com] HTTPSConnectionPool(host='macromedia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc5eb07df90>, 'Connection to macromedia.com timed out. (connect timeout=None)'))
[msedge.net] HTTPSConnectionPool(host='msedge.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc5eb38b9d0>, 'Connection to msedge.net timed out. (connect timeout=None)'))
[nytimes.com] HTTPSConnectionPool(host='www.nytimes.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc5eb07c690>, 'Connection to www.nytimes.com timed out. (connect timeout=None)'))
[tumblr.com] HTTPSConnectionPool(host='tumblr.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc5e9525810>, 'Connection to tumblr.com timed out. (connect timeout=None)'))
